version: '3.2'
services:
  apache:
    build: .
    env_file:
    - config/app.env
    - config/mysql.env
    ports:
    - 8088:80
    volumes:
    - type: bind
      source: .
      target: /var/www/html
  mysql:
    image: mysql:5.7
    env_file: config/mysql.env
    # see https://hub.docker.com/_/mysql/
    volumes:
      - ./dumps/zcu_demo.sql:/docker-entrypoint-initdb.d/zcu_demo.sql
  adminer:
    image: adminer # official image is OK
    ports:
    - 8086:8080
    depends_on:
    - mysql
