version: '3.2'
services:
  # app:
  #   image: intraworlds/zcu-security-demo:1.0
  #   build: .
  #   environment:
  #     # btw. this is also security issue - never put a password into VCS! - this is OK for demo purpose
  #     DB_DATA_PATH: /var/lib/mysql
  #     DB_ROOT_PASS: ""
  #     DB_USER: zcu_demo
  #     DB_PASS: password
  # see https://hub.docker.com/_/php/
  apache:
    build: .
    env_file:
    - config/app.env
    - config/mysql.env
    ports:
    - 8088:80
    volumes:
    - type: bind
      source: .
      target: /var/www/html
  mysql:
    image: mysql:5.7
    env_file: config/mysql.env
    # see https://hub.docker.com/_/mysql/
    volumes:
      - ./dumps/:/docker-entrypoint-initdb.d
  adminer:
    image: adminer # official image is OK
    ports:
    - 8086:8080
    depends_on:
    - mysql
